# .github/workflows/douban.yml
name: Douban Get Json
on:
  schedule:
    - cron: '7 1,5,10,14,17,22 * * *'
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: '获取豆瓣Json数据'
        type: boolean
        required: true
        default: true

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: delete old file
      run: |
        rm -rf ./data

    - name: movie
      uses: Katou-Kouseki/doumark-action@master
      with:
        id: 166535290
        type: movie
        format: json
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './data/douban'
